name: Daily Book Scraper

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite (UTC)

jobs:
  update-books:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala pacotes se houver requirements.txt

      - name: Run scraper script
        run: python main.py  # Substitua "script.py" pelo nome do seu script

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/books.jsx
          git commit -m "Atualiza dados dos livros"
          git push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
